name: Node setup
description: Set up Node and install dependencies with a clean, reproducible install.
runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22.16.0
        cache: npm
    - name: Install dependencies
      shell: bash
      run: npm ci
